/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M17
 * Generated at: 2017-03-14 17:33:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import servlet.*;

public final class searchauthor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Object obj=session.getAttribute("giohang");
	if(obj!=null){
	    Giohang giohang=(Giohang)obj;
	    ArrayList<Sanpham> dssp=giohang.getSPGiohang();
	    if(dssp.size()>0){

      out.write("\r\n");
      out.write("<table align=\"center\" border=\"1\" width=\"95%\">\r\n");
      out.write("    <tr>\r\n");
      out.write("        <th>STT</th>\r\n");
      out.write("        <th>Tên sách</th>\r\n");
      out.write("        <th>Tên tác giả</th>\r\n");
      out.write("        \r\n");
      out.write("        <th>Đơn giá</th>\r\n");
      out.write("        <th>Số lượng hiện còn trong kho</th>\r\n");
      out.write("       \r\n");
      out.write("        <th></th>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    ");
int i=1;
    for(Sanpham sp:dssp){
    	
    	 String ms=sp.getId();
    	 String tua=sp.getTitle();
         String tgia=sp.getAuthor();
        
         double dg=sp.getPrice();
         int qty =sp.getQty();
         
        
      out.write("\r\n");
      out.write("      \r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>");
      out.print(ms);
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(tua);
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(tgia);
      out.write("</td>\r\n");
      out.write("            \r\n");
      out.write("            <td>");
      out.print(dg);
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(qty);
      out.write("</td>\r\n");
      out.write("           \r\n");
      out.write("            <td>\r\n");
      out.write("                <form action=\"Controller\" method=\"post\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"trahang\"/>\r\n");
      out.write("                    <input type=\"hidden\" name=\"mssp\" value=\"");
      out.print(ms);
      out.write("\"/>\r\n");
      out.write("                    <input type=\"submit\" value=\"Trả hàng\"/>\r\n");
      out.write("                </form>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    ");
}
      out.write("\r\n");
      out.write("    </table>\r\n");
      out.write("    <br/>\r\n");
      out.write("        <center>\r\n");
      out.write("            <form method=\"post\" action=\"Controller\">\r\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"checkout\"/>\r\n");
      out.write("                <input type=\"submit\" value=\"Check out\"/>\r\n");
      out.write("            </form>\r\n");
      out.write("        </center>\r\n");
      out.write("   ");
}
   }

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
